version: '2'
services:
    webar-app:
        build: .
        ports:
            - 3001:3001
        container_name: webar-app
        links:
            - webar-mongodb
            - webar-mysqldb
        depends_on:
            - webar-mongodb
            - webar-mysqldb
    webar-mysqldb:
        image: mysql:5.7.22
        ports:
              - 4306:3306
        environment:
              - MYSQL_DATABASE=webarapp
              - MYSQL_USER=admin
              - MYSQL_PASSWORD=admin
              - MYSQL_ROOT_PASSWORD=root
        container_name: webar-mysqldb
    webar-mongodb:
        image: mongo:3.2.21
        container_name: webar-mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        ports:
            - 27017:27017

